
spring:
  server:
    port: 8081
    servlet.contextPath: '/@name@'

  h2:
    console:
      enabled: true
      path: /h2
      url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=TRUE
      username: sa
      password: password
      driverClassName: org.h2.Driver
      jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect









