
spring:
server:
  port: 8888
  #servlet.contextPath: '/@name@'
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true

  h2:
    console.enabled: true







