
#server before spring props, on same level
server:
  port: 8888
  servlet.contextPath: '/@name@'


spring:
  h2:
   console:
     enabled: true
     path: /h2
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver




